### PR TITLE
Update Galea v4 emulator to control sampling rate

### PR DESCRIPTION
**Pull request by retiutut**

### CODE REVIEW

**Comment by Andrey1994** [comment]
part about adding new command is fine but I dont get the motivation for debug messages and all these calculations, seems like it doesnt change anything in terms of sampling rate

**Comment by retiutut** [comment]
> part about adding new command is fine but I dont get the motivation for debug messages and all these calculations, seems like it doesnt change anything in terms of sampling rate

It works as expected on the receiving end.

**Comment by retiutut** [comment]
@Andrey1994 @philippitts Can we review and merge? This has many important additions.

**Comment by Andrey1994** [comment]
I've fixed failed alpine test and removed some logic which made it too complicated for simple emulator. The proper tracking and emulation of sampling rate behaviour would require another approach and more refactoring. And after all sampling rate matching is not a requirement for functional high level model, keeped logic for channel settings and notifications for sampling rate commands

**Pull request merged**
