### PR TITLE
change oymotion resolution to 12bits

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

Restore 12bits resolution for oymotion devices(based on email thread). @matthijscox could you review and check that it works fine?

### CODE REVIEW

**Comment by matthijscox** [comment]
I used this branch to compile the libs. 

Successfully connected the GFORCE_PRO_BOARD, could get board data without any sign of problems.

Then stopped/released/disconnected everything, including the dongle. 
Reconnected with the GFORCE_DUAL_BOARD. Could again succesfully connect and get board data.

@Andrey1994 it looks good from my side!

**Review by matthijscox — APPROVED** [review]
All good

**Comment by Andrey1994** [comment]
Great! To double check are you sure that correct libraries were used? Emg values should be greater than 256

**Comment by Andrey1994** [comment]
And did you test it using new gforce pro?

**Comment by matthijscox** [comment]
Yes, this is the gForcePro+, which works fine with the GFORCE_PRO_BOARD.

Here's a snippet of data, but that's already in microvolts right? Can you already see from this if it surpasses the 8bits limit?
image

Just to try, I did a unique, and there are more than 256 types of values:
image

**Comment by Andrey1994** [comment]
<<but that's already in microvolts right? Can you already see from this if it surpasses the 8bits limit?

its definitely 12 bits(for 8 bits max value here is 256, or maybe even 128 if its signed) .
And its the only board where we return non uV value, mostly because I dont know equation to convert it to uV. I asked about it here https://github.com/oymotion/gForceSDKCXX/issues/4 but still dont fully understand how to convert that

**Comment by Andrey1994** [comment]
does it also work for gforce dual?

**Comment by Andrey1994** [comment]
And when you run `import BrainFlow` you saw "using local libraries" didnt you?

**Comment by matthijscox** [comment]
Yes it works for gForceDual and yes I saw the local library usage. I copied the local /lib from the build process to the julia brainflow folder.

**Pull request merged**
