### PR TITLE
Changes to support brainflow CSharp on Linux using Mono framework

### PR DESCRIPTION
**Pull request by Andrey1994**
Its a copy of #133 but without merge conflicts

1) Added PlatformHelper.cs
- Provides a single efficient place to determine correct library environment

2) Modified  board_controller_library.cs and data_handler_library.cs and ml_module_library.cs
- *LibraryLinux was added to mirror *Library32 and *Library64 pattern
- Functions were modified to switch on LibraryEnvironment instead of if(64){}else{}

Ran all C# test projects on:
- Windows = all tests pass
- Linux 64 bit = all tests pass
- Linux 32 bit ARM (Raspbian Buster) = one test fails to run to completion
(however, the analogous  C++ test also fails in same way when run on Raspbian Buster)

Please see this report for details and proof of tests run:  https://docs.google.com/document/d/e/2PACX-1vQcvG-C1hVSkCLoHbMSsg8918PqG82ONWmkRDfdvXrQj6RBujD3YWY8E5pUJHj8_Tr8aY6-C0Q16q--/pub

### CODE REVIEW

**Comment by Andrey1994** [comment]
@GrahamBriggs I pushed your commit to add Unix C# support to this branch, to avoid fixing minor merge conflicts between original version and openbci fork.
There are minor changes in docs and in CI and if you branch from brainflow-dev you can merge your code to openbci fork without conflicts but not vice versa. Next time fork from this one.

I hope you dont mind if I close your original PR with conflicts and we continue here

**Comment by Andrey1994** [comment]
It looks good and I like PlatformHelper, a few improvements which I would like to add here:

* Handle MacOS correctly, lib name for MacOS is different, its smth like BoardController.dylib, not .so
* Add tests for it to new CI for Unix
* Add instructions how to build it using Mono to docs, I suppose you also built Accord using Mono right?
* It doesnt follow existing code style

I can take care of them or if you want to fix some or all of them by yourself let me know

**Comment by GrahamBriggs** [comment]
Andrey

Thank you for reviewing the pull request.

Your improvements all make sense. I believe it would be most efficient if you made the improvements in your code base and I will discard my repo and start using the official again when you have it out there.  

I also agree that the other pull request can be canceled.  I just started working with your wonderful libraries and I did not realize until after that brainflow dev was different than the Open BCI brainflow library that I cloned when I got started.

Regarding Build on Mono

I did not build the Accord.dll.  It is included as a nuget package in the solution, so VisualStudio or MonoDevelop took care of that detail for me.

FWIW, my development procedure for using Mono on Raspberry Pi.

1) Do most of the work using the PC build.  Use a proxy for GPIO pins in the project requires - for example see WiringPiProxy.cs in my brainHat project  https://github.com/GrahamBriggs/bcibeginner/tree/master/CSharp/WiringPiWrapper <https://github.com/GrahamBriggs/bcibeginner/tree/master/CSharp/WiringPiWrapper> ).
2) Build on my PC using visual studio. Go to the output directory, select the .exe, *.dll, and *.config files
3) Open network file share to the Pi, copy these program bits to this folder
4) Open terminal on the Pi, “mono MyProgram.exe”

I start all of my programs by adding a good logging framework (I like log4Net for no other reason than I learned it first and it works).  This is usually sufficient to debug any problems that may be quirky only on the Pi.  On the rare occasion I am are tracking down a bug that only happens on the Pi and I can’t diagnose from the logs, I will use MonoDevelop on the Pi to run and debug the code.

To setup CI, you can use xbuild like you would use msbuild to compile the solution from the command line.

Regarding proper naming for MacOS - 

Sounds good, I don’t know anything about how mono runs on Mac OS so I will be curious to see what this looks like.

I assume that iOS will identify as Unix in this environment switch.  It is my understanding that library names on iOS follow the lib*.so syntax.

I ask because as my next adventure I am working on a mobile application that receives and processes data from the Cyton board. I am using a Xamarin forms cross platform app solution, and I have a simple android application running that can call libBrainFlowLibraries.so using my wrapper (video here https://youtu.be/k3NY0DbXRWM <https://youtu.be/k3NY0DbXRWM> )

I am interested to see if I can get it also to work on iOS.  Do you know if anyone has built the libraries for iOS and shared the project (or better yet the binaries), it would be great to skip that step because compiling the C++ into the library files for iOS is just one extra pain I would love to avoid.

Thank you again for taking care of this pull request.

Best Regards



GB
=-=-=-=-=-=-=
Graham Briggs <mailto:GrahamBriggs@littlebytesofpi.com>
LittleBytesOfPi.com <http://littlebytesofpi.com/>

**Comment by GrahamBriggs** [comment]
Andrey

This sounds fine. I sent a longer reply to your other mail.

Thank you very much for your time and attention.

GB
=-=-=-=-=-=-=
Graham Briggs <mailto:GrahamBriggs@littlebytesofpi.com>
LittleBytesOfPi.com <http://littlebytesofpi.com/>

**Comment by Andrey1994** [comment]
Hi,I dont think that someone tried it on IOS. I suppose we need to develop swift binding for it and more likely add/fix some ifdefs in cpp code Отправлено с устройства Galaxy
-------- Исходное сообщение --------От: Graham Briggs <notifications@github.com> Дата: 20.11.2020  05:39  (GMT+03:00) Кому: brainflow-dev/brainflow <brainflow@noreply.github.com> Копия: Andrey Parfenov <a1994ndrey@gmail.com>, Author <author@noreply.github.com> Тема: Re: [brainflow-dev/brainflow] Changes to support brainflow CSharp on Linux using Mono framework (#140) 

Andrey



Thank you for reviewing the pull request.



Your improvements all make sense. I believe it would be most efficient if you made the improvements in your code base and I will discard my repo and start using the official again when you have it out there.  



I also agree that the other pull request can be canceled.  I just started working with your wonderful libraries and I did not realize until after that brainflow dev was different than the Open BCI brainflow library that I cloned when I got started.



Regarding Build on Mono



I did not build the Accord.dll.  It is included as a nuget package in the solution, so VisualStudio or MonoDevelop took care of that detail for me.



FWIW, my development procedure for using Mono on Raspberry Pi.



1) Do most of the work using the PC build.  Use a proxy for GPIO pins in the project requires - for example see WiringPiProxy.cs in my brainHat project  https://github.com/GrahamBriggs/bcibeginner/tree/master/CSharp/WiringPiWrapper <https://github.com/GrahamBriggs/bcibeginner/tree/master/CSharp/WiringPiWrapper> ).

2) Build on my PC using visual studio. Go to the output directory, select the .exe, *.dll, and *.config files

3) Open network file share to the Pi, copy these program bits to this folder

4) Open terminal on the Pi, “mono MyProgram.exe”



I start all of my programs by adding a good logging framework (I like log4Net for no other reason than I learned it first and it works).  This is usually sufficient to debug any problems that may be quirky only on the Pi.  On the rare occasion I am are tracking down a bug that only happens on the Pi and I can’t diagnose from the logs, I will use MonoDevelop on the Pi to run and debug the code.



To setup CI, you can use xbuild like you would use msbuild to compile the solution from the command line.



Regarding proper naming for MacOS - 



Sounds good, I don’t know anything about how mono runs on Mac OS so I will be curious to see what this looks like.



I assume that iOS will identify as Unix in this environment switch.  It is my understanding that library names on iOS follow the lib*.so syntax.



I ask because as my next adventure I am working on a mobile application that receives and processes data from the Cyton board. I am using a Xamarin forms cross platform app solution, and I have a simple android application running that can call libBrainFlowLibraries.so using my wrapper (video here https://youtu.be/k3NY0DbXRWM <https://youtu.be/k3NY0DbXRWM> )



I am interested to see if I can get it also to work on iOS.  Do you know if anyone has built the libraries for iOS and shared the project (or better yet the binaries), it would be great to skip that step because compiling the C++ into the library files for iOS is just one extra pain I would love to avoid.



Thank you again for taking care of this pull request.



Best Regards







GB

=-=-=-=-=-=-=

Graham Briggs <mailto:GrahamBriggs@littlebytesofpi.com>

LittleBytesOfPi.com <http://littlebytesofpi.com/>

**Comment by Andrey1994** [comment]
@GrahamBriggs merged

**Pull request merged**
