### PR TITLE
Muse S bled

### PR DESCRIPTION
**Pull request by Andrey1994**

### CODE REVIEW

**Comment by Andrey1994** [comment]
for some reason callbacks\BLE notifications do not work, no idea why

**Comment by Andrey1994** [comment]
@matthijscox I've tested it using muse s, could you check that it works(more or less) for your muse s and after that check it for muse 2?

Dongle is needed(the same as for ganglion), board ids are 21(muse s) and 22(muse 2)

Rarely I saw problems with a dongle or sync_timeout_error when for some reason scanning for characteristics doesnt work. But its rarely and I dont see any problems in code

**Comment by matthijscox** [comment]
Ok, I compiled the code from the muse_s_bled branch using the build_win64.cmd, copied installed64/lib into my julia-package/brainflow/lib.

Saw these during compilation, seems good.
image

Then used the bled112 dongle and turned on the Muse S.

Then ran the following:
```
using BrainFlow
BrainFlow.enable_dev_logger(BrainFlow.BOARD_CONTROLLER)
params = BrainFlowInputParams(serial_port="COM5")
#board_id = BrainFlow.GFORCE_DUAL_BOARD
board_id = BrainFlow.MUSE_S_BLED_BOARD
board_shim = BrainFlow.BoardShim(board_id, params)
BrainFlow.prepare_session(board_shim)
[2021-06-18 21:35:31.374] [board_logger] [info] incoming json: {"serial_port":"COM5","mac_address":"","ip_address":"","ip_port":0,"ip_protocol":0,"other_info":"","timeout":0,"serial_number":"","file":""}
[2021-06-18 21:35:31.375] [board_logger] [trace] Board object created 21
[2021-06-18 21:35:31.429] [board_logger] [debug] Library is loaded

BrainFlow.start_stream(board_shim)
BrainFlow.get_board_data(board_shim)'
2028×10 Matrix{Float64}:
 5761.0  -1000.0      -50.7812    865.234   -1000.0    0.113892  0.0169067  -0.986511  1.62405e9  0.0
 5761.0   -132.324   -790.039     632.812    -160.156  0.113892  0.0169067  -0.986511  1.62405e9  0.0
 5761.0   -857.422    439.941    -223.145    -888.184  0.113892  0.0169067  -0.986511  1.62405e9  0.0
    ⋮                                                  ⋮
 5929.0    523.438    532.715   -1000.0      -952.148  0.117981  0.019104   -0.991394  1.62405e9  0.0
 5929.0   -840.332   -845.215      89.8438    331.543  0.117981  0.019104   -0.991394  1.62405e9  0.0
 5929.0  -1000.0    -1000.0      -782.715    -772.949  0.117981  0.019104   -0.991394  1.62405e9  0.0
```

Looking good!!

**Comment by Andrey1994** [comment]
Good news! Let's try Muse2, I've bought MuseS only and didnt test Muse 2 at all

btw you dont need to copypaste installed65\libs folder cmake should do it automatically

**Comment by matthijscox** [comment]
Muse 2 also seems to be working!

```
julia> BrainFlow.prepare_session(board_shim)
[2021-06-18 21:44:08.026] [board_logger] [info] incoming json: {"serial_port":"COM5","mac_address":"","ip_address":"","ip_port":0,"ip_protocol":0,"other_info":"","timeout":0,"serial_number":"","file":""}
[2021-06-18 21:44:08.026] [board_logger] [trace] Board object created 22
[2021-06-18 21:44:08.027] [board_logger] [debug] Library is loaded

julia> BrainFlow.start_stream(board_shim)
[2021-06-18 21:44:10.650] [board_logger] [debug] use stub streamer

julia> BrainFlow.get_board_data(board_shim)'
13020×10 Matrix{Float64}:
    1.0  -1000.0    -1000.0     -1000.0    -1000.0    0.0        0.0        0.0       1.62405e9  0.0
    1.0   -205.078   -596.68     -834.473   -199.707  0.0        0.0        0.0       1.62405e9  0.0
    1.0    999.023    789.551     499.023    992.188  0.0        0.0        0.0       1.62405e9  0.0
    ⋮                                                 ⋮
 1085.0    233.887     43.9453  -1000.0     -206.055  0.313599  -0.0644531  0.947571  1.62405e9  0.0
 1085.0  -1000.0    -1000.0      -215.332  -1000.0    0.313599  -0.0644531  0.947571  1.62405e9  0.0
 1085.0   -102.051   -441.406    -915.039   -937.988  0.313599  -0.0644531  0.947571  1.62405e9  0.0
```

**Comment by Andrey1994** [comment]
Looks great, thanks for testing!
I will run a few more tests and create new release during this weekend

**Comment by matthijscox** [comment]
For the fun of it, plotted the 4 EEG channels. (my real time plotting still works like a charm)

At least I caught an eye blink in the two sensors on the forehead (ch1 and ch4)

image

**Comment by matthijscox** [comment]
Great work, Andrey!

**Pull request merged**
