### PR TITLE
Update amplifier.h

### PR DESCRIPTION
**Pull request by fullflyt**
Added #include <cstdint> in line 56

### CODE REVIEW

**Comment by Andrey1994** [comment]
I dont understand why this header is needed here, I dont see any non default int like types in it. Which error does it solve? And even if it should be a part of this header, I believe it should be added together with system includes a couple of lines above

**Comment by Andrey1994** [comment]
ah, ok there is uint64_t, is it the issue? If its the case lets just move this include up to system includes

**Comment by fullflyt** [comment]
Hi,

The uname output:
(eeg2) ***@***.***:~/Projects/EEG2/brainflow/tools$ uname -a
Linux localhost.localdomain 6.6.0-1003-apple-arm #3-Ubuntu SMP
PREEMPT_DYNAMIC Wed Dec 27 01:40:02 UTC 2023 aarch64 aarch64 aarch64
GNU/Linux

I run ubuntu on a Mac Powerbook M1 and a Orange Pi 5 plus.

I downloaded brainflow again and ran with this output w/o the cstdint
statement:
/home/ubuntu/Projects/EEG2/brainflow/third_panrty/ant_neuro/eemagine/sdk/amplifier.h:94:46:
error: uint64_t was not declared in this scope
   94 |                             if (ref_mask & ((uint64_t)1 <<
ref_counter))
      |                                              ^~~~~~~~
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:56:1:
note: uint64_t is defined in header <cstdint>; did you forget to #include
<cstdint>?
   55 | #include <eemagine/sdk/stream.h>
  +++ |+#include <cstdint>
   56 |
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:94:55:
error: expected ) before numeric constant
   94 |                             if (ref_mask & ((uint64_t)1 <<
ref_counter))
      |                                                       ^
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:94:44:
note: to match this (
   94 |                             if (ref_mask & ((uint64_t)1 <<
ref_counter))
      |                                            ^
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:98:31:
error: expected ) before ref_counter
   98 |                             ++ref_counter;
      |                               ^~~~~~~~~~~
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:94:32:
note: to match this (
   94 |                             if (ref_mask & ((uint64_t)1 <<
ref_counter))
      |                                ^
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:101:46:
error: uint64_t was not declared in this scope
  101 |                             if (bip_mask & ((uint64_t)1 <<
bip_counter))
      |                                              ^~~~~~~~
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:101:46:
note: uint64_t is defined in header <cstdint>; did you forget to #include
<cstdint>?
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:101:55:
error: expected ) before numeric constant
  101 |                             if (bip_mask & ((uint64_t)1 <<
bip_counter))
      |                                                       ^
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:101:44:
note: to match this (
  101 |                             if (bip_mask & ((uint64_t)1 <<
bip_counter))
      |                                            ^
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:105:31:
error: expected ) before bip_counter
  105 |                             ++bip_counter;
      |                               ^~~~~~~~~~~
/home/ubuntu/Projects/EEG2/brainflow/third_party/ant_neuro/eemagine/sdk/amplifier.h:101:32:
note: to match this (
  101 |                             if (bip_mask & ((uint64_t)1 <<
bip_counter))


I reran once more with the #include <cstdint> statement in amplifier.h and
it worked. You know more about the architecture, so if the #include
<cstdint> should be moved higher up in the architecture, it would probably
work.


Warm regards/Med vennlig hilsen
Einar Jørgensen
Daglig Lederctsdint
Fullflyt AS

Mobil: +47 982 33 894 <982%2033%20894>
email: einar@ ***@***.***>fullflyt.no


tir. 2. apr. 2024 kl. 23:19 skrev Andrey Parfenov ***@***.***

**Comment by Andrey1994** [comment]
thanks

**Pull request merged**
