### PR TITLE
Adding Bitalino Board_Id

### PR DESCRIPTION
**Pull request by alchemy-abc**
Adding BITalino BLE Board with 100Hz for sample rate and 2 active channel for EEG

### CODE REVIEW

**Comment by Andrey1994** [comment]
Setup this https://brainflow.readthedocs.io/en/stable/BrainFlowDev.html#code-style to fix code style check, also here https://github.com/brainflow-dev/brainflow/pull/194/checks?check_run_id=1613714099 you can check what exactly doesnt match existing code style

**Comment by alchemy-abc** [comment]
I checked [https://github.com/brainflow-dev/brainflow/pull/194/checks?check_run_id=1613714099] and I couldn't understand what is the wrong 
image

**Comment by Andrey1994** [comment]
It checks code style, there is a tool which automatically formats the code based on some rules. Rules are in file .clang-format you should configure visual studio to use this formatter.

This check says that it was not configured and code does not match these rules

**Comment by Andrey1994** [comment]
https://devblogs.microsoft.com/cppblog/clangformat-support-in-visual-studio-2017-15-7-preview-1/

**Comment by Andrey1994** [comment]
Here https://github.com/brainflow-dev/brainflow/pull/194#issuecomment-751576858 it shows you how code style should be fixed using - and +(its git diff in fact)

**Comment by Andrey1994** [comment]
I will fix it myself

**Pull request merged**
