### PR TITLE
Add brainalive device

### PR DESCRIPTION
**Pull request by Sarthak031**
@Andrey1994 I have added my BrainAlive device into Brainflow Please check it out to the latest commit. As you had suggested the GanglionBLE code so I have added the code according to the suggested Ganglion Board But I Have some problem in DLLLoader please help me in this

### CODE REVIEW

**Comment by Andrey1994** [comment]
I am working on the common BLE helper in [ble branch](https://github.com/brainflow-dev/brainflow/tree/ble).

It's in the early dev stage for now, you are welcome to help me with implementation and testing. It should become a standard way to integrate BLE devices wo dongle in BrainFlow

**Comment by Sarthak031** [comment]
> I am working on the common BLE helper in [ble branch](https://github.com/brainflow-dev/brainflow/tree/ble).
> 
> It's in the early dev stage for now, you are welcome to help me with implementation and testing. It should become a standard way to integrate BLE devices wo dongle in BrainFlow

Ok, I am ready to help you with this.

**Comment by Andrey1994** [comment]
Great, there is BLELibBoard class, you can try to inherit your board class from this one and use its methods. I have not tested it yet

**Comment by Sarthak031** [comment]
> Great, there is BLELibBoard class, you can try to inherit your board class from this one and use its methods. I have not tested it yet
Ok, I will try and let you know after the test.

**Comment by Sarthak031** [comment]
@Andrey1994 Please review my pull request. I have fixed some minor issues in the code.

**Comment by Andrey1994** [comment]
I want to complete the integration of the new BLE library and use it for Muse devices in #350 after that you will be able to use it in this PR

**Review by Andrey1994 — CHANGES_REQUESTED** [review]
The new ble library is almost ready and soon will be merged, scanning, connection and notifications work(so far I've tested it only on Windows) you can start working on it

**Comment by Andrey1994** [comment]
closing this PR(no updates and need more work), feel free to create a new one and make sure that new BLE lib is used

**Pull request closed without merging**
